apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: team-c

resources:
  - ../../base
  - webhook-patch.yaml

patches:
  - path: web-ingress-patch.yaml
    target:
      kind: Ingress
      name: web
  - path: service-patch.yaml
    target:
      kind: Service
      name: web
