apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: team-c

resources:
  - ../../base

patches:
  - path: web-ingress-patch.yaml
    target:
      kind: Ingress
      name: web
  - path: sa-patch.yaml # 보안패치 추가한 파일
    target:
      kind: Deployment
      name: api
