apiVersion: v1
kind: Pod
metadata:
  name: s3-noauth-test
  namespace: team-c
spec:
  serviceAccountName: default
  containers:
    - name: awscli
      image: amazon/aws-cli:2.15.0
      command: ["sleep", "3600"]
      resources:
        requests:
          cpu: 25m
          memory: 64Mi
        limits:
          cpu: 50m
          memory: 128Mi
