apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: team-c
spec:
  type: NodePort #clusterIP에서 변경
  selector:
    app.kubernetes.io/name: web
  ports:
    - protocol: TCP #작성하지 않아도 default로 적용됨
      port: 80
      targetPort: 80
