apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: workload-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: workload-secrets
    creationPolicy: Owner
  data:
    - secretKey: redis-url
      remoteRef:
        key: /training/workload/shared
        property: redisUrl
    - secretKey: external-postgres-password
      remoteRef:
        key: /training/workload/shared
        property: externalPostgresPassword
    - secretKey: redis-password
      remoteRef:
        key: /training/workload/shared
        property: redisPassword
