apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: team-a

resources:
  - ../../base

  - default-serviceaccount.yaml
patches:
  - path: web-ingress-patch.yaml
    target:
      kind: Ingress
      name: web
  - path: default-sa-token-patch.yaml
