apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: app-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-runtime-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: app-secrets-manager
    kind: SecretStore
  target:
    name: app-runtime-secrets
    creationPolicy: Owner
  data:
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: /eks-secure-infra/app/redis
        property: password
    - secretKey: EXTERNAL_POSTGRES_PASSWORD
      remoteRef:
        key: /eks-secure-infra/app/external-postgres
        property: password
