apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: team-d

resources:
  - ../../base

patches:
  - path: web-ingress-patch.yaml
    target:
      kind: Ingress
      name: web
  - path: web-root-restriction-patch.yaml
    target:
      kind: Deployment
      name: web
