apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: lab1-gp3-unencrypted
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  encrypted: "true"
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Delete
