# 권한 정의(Role)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: team-dev
  name: web-pod-reader
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"] # 읽기 권한만 부여
---
# Role-Binding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: web-rb
  namespace: team-dev
subjects:
  - kind: ServiceAccount
    name: web-workload
    namespace: team-dev
roleRef:
  kind: Role
  name: web-pod-reader
  apiGroup: rbac.authorization.k8s.io
