cni:
  chainingMode: aws-cni
  exclusive: false

enableIPv4Masquerade: false
routingMode: native

hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true
  metrics:
    enabled:
      - dns:query;ignoreAAAA
      - drop
      - tcp
      - flow
      - http

operator:
  replicas: 1
