apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: team-b

resources:
  - ../../base

patches:
  - path: web-ingress-patch.yaml
    target:
      kind: Ingress
      name: web
  - path: db-patch.yaml
    target:
      kind: StatefulSet
      name: db
  - path: api-patch.yaml
    target:
      kind: Deployment
      name: api